dataset:
  train:
    #name: mixed
    name: hypersim
    # prob_ls: [0.9, 0.1]
    disp_name: hypersim_train
    dir: hypersim/train # ${BASE_DATA_DIR}/(.)
    filenames: data/hypersim/train/filename_list_train.txt
    resize_to_hw:
    - 480
    - 640

#    dataset_list:
#    - name: hypersim
#      disp_name: hypersim_train
##      dir: hypersim/hypersim_processed_train.tar
##      filenames: data_split/hypersim/filename_list_train_filtered.txt
#      # ./data/?
#      dir: hypersim/train
#      filenames: data/hypersim/train/filename_list_train.txt
#      resize_to_hw:
#      - 480
#      - 640

##    - name: vkitti
##      disp_name: vkitti_train
##      dir: vkitti/vkitti.tar
##      filenames: data_split/vkitti/vkitti_train.txt
##      kitti_bm_crop: true
##      valid_mask_crop: null